import "./globals.css";
import Script from "next/script";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { cn } from "@/lib/utils";

import { UserProvider } from "@/contexts/user";
import { ToastProvider } from "@/contexts/toast";
import ToastMessage from "@/components/application/toast";
import { EventsProvider } from "@/contexts/events";

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-G7NWPZKQ2S"
        ></Script>
        <Script id="gtag-init" strategy="afterInteractive">
          {`     window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-G7NWPZKQ2S');
                    `}
        </Script>
      </head>
      <body className={cn(plusJakartaSans.className)}>
        {" "}
        <UserProvider>
          <ToastProvider>
            <EventsProvider>
              <ToastMessage />
              {children}
            </EventsProvider>
          </ToastProvider>
        </UserProvider>
      </body>
    </html>
  );
}
